"""Test migration

Revision ID: d8195c057a2d
Revises: 
Create Date: 2023-02-12 22:18:40.020181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8195c057a2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selectedheroes',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('selectedheroes')
    # ### end Alembic commands ###
